services:
  - type: web
    name: para-home
    runtime: python
    plan: free
    buildCommand: ./scripts/check.sh
    startCommand: ./scripts/render-start.sh
    healthCheckPath: /api/v1/health

    envVars:
      - key: PARA_SUPABASE_URL
        value: https://fqkbvxutsijruyawzxxo.supabase.co
      - key: PARA_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_aKSE87nlJmUddelmwAwa9Q_5sz5ZESY
      - key: PARA_EMAILJS_SERVICE_ID
        value: service_rozuv2c
      - key: PARA_EMAILJS_TEMPLATE_ID
        value: template_xd50wdh
      - key: PARA_EMAILJS_PUBLIC_KEY
        value: Vcb2UJ9zNsxvhEajq
      - key: PARA_EMAILJS_PRIVATE_KEY
        sync: false
      - key: PARA_EMAILJS_ORIGIN
        sync: false
